# Gaussian Naive Bayes Classification using Titanic Dataset
## Objective

The goal of this notebook is to build a Gaussian Naive Bayes Classification model using the Titanic dataset and predict passenger survival.

## Dataset

The Titanic dataset contains passenger information from the Titanic ship disaster.

### Features Available:
- Passenger Class
- Gender
- Age
- Fare
- Family Information
- Cabin Information
- Embarked Port

### Target Variable:
- Survived
    - 0 → Did Not Survive
    - 1 → Survived

This is a binary classification problem.

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

## Load Titanic Dataset

The Titanic dataset is loaded using pandas.

In [5]:
df=pd.read_csv('titanic.csv')
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

## Removing Unwanted Features

Some columns are removed because they are not useful for prediction or contain too many missing values.

Removed Columns:
- PassengerId
- Name
- SibSp
- Parch
- Ticket
- Cabin
- Embarked

In [6]:
#removing unwanted features
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'], axis=1, inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

## Creating Independent and Dependent Variables

### Input Features
- Passenger Class
- Gender
- Age
- Fare

### Target Variable
- Survival Status

In [8]:
#Dependent & Independent Variables
target=df.Survived
input=df.drop('Survived', axis=1)

## Handling Categorical Variables

Machine learning models cannot directly understand categorical text values like male and female.

`get_dummies()` is used to convert categorical columns into numerical format.

In [12]:
#handling categorical columns 
dummies=pd.get_dummies(input.Sex)
dummies.head()

   female   male
0   False   True
1    True  False
2    True  False
3    True  False
4   False   True

## Concatenating Dummy Variables

The encoded gender columns are combined with the original dataset.

In [20]:
#dropping sex column
input.drop('Sex', axis=1,inplace=True)
input.head()

   Pclass   Age     Fare  female   male  female   male
0       3  22.0   7.2500   False   True   False   True
1       1  38.0  71.2833    True  False    True  False
2       3  26.0   7.9250    True  False    True  False
3       1  35.0  53.1000    True  False    True  False
4       3  35.0   8.0500   False   True   False   True

## Dropping Original Categorical Column

The original `Sex` column is removed after encoding because the model now uses the numerical dummy variables.

In [19]:
input=pd.concat([input,dummies],axis=1)
input.head()

   Pclass     Sex   Age     Fare  female   male  female   male
0       3    male  22.0   7.2500   False   True   False   True
1       1  female  38.0  71.2833    True  False    True  False
2       3  female  26.0   7.9250    True  False    True  False
3       1  female  35.0  53.1000    True  False    True  False
4       3    male  35.0   8.0500   False   True   False   True

## Checking Missing Values

The dataset is checked for null values before model training.

The `Age` column contains missing values.

In [21]:
#check for missing values 
input.isna().sum()

Pclass      0
Age       177
Fare        0
female      0
male        0
female      0
male        0
dtype: int64

## Handling Missing Values

Missing values in the `Age` column are replaced using the mean age value.

This process is called Mean Imputation.

In [23]:
input['Age']=input['Age'].fillna(input['Age'].mean())

In [24]:
input.isna().sum()

Pclass    0
Age       0
Fare      0
female    0
male      0
female    0
male      0
dtype: int64

## Train-Test Split

The dataset is divided into:

- Training Data → used to train the model
- Testing Data → used to evaluate model performance

A test size of 30% is used.

In [25]:
#splitting data for training & prediction
X_train, X_test, y_train, y_test=train_test_split(input,target,test_size=0.3)

In [26]:
X_train.shape

(623, 7)

In [27]:
X_test.shape

(268, 7)

## Gaussian Naive Bayes Classifier

Gaussian Naive Bayes is a supervised machine learning classification algorithm based on Bayes Theorem.

It assumes:
- features are independent
- numerical features follow Gaussian (Normal) distribution

GaussianNB works well for:
- small datasets
- fast classification tasks
- probabilistic predictions

In [29]:
#creating a object of GaussianNB 
model=GaussianNB()

## Model Training

The Gaussian Naive Bayes model is trained using the training dataset.

In [30]:
#fitting model
model.fit(X_train, y_train)

GaussianNB()

## Model Accuracy

The model achieved an accuracy score of approximately 81%.

This means the model correctly predicted survival outcomes for most passengers in the test dataset.

In [31]:
#model scores - used to find accuracy 
model.score(X_test, y_test)

0.8097014925373134

Internally does compare predicted and actual labels
y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

In [32]:
X_test[:10]

     Pclass        Age      Fare  female   male  female   male
665       2  32.000000   73.5000   False   True   False   True
107       3  29.699118    7.7750   False   True   False   True
589       3  29.699118    8.0500   False   True   False   True
884       3  25.000000    7.0500   False   True   False   True
499       3  24.000000    7.7958   False   True   False   True
380       1  42.000000  227.5250    True  False    True  False
358       3  29.699118    7.8792    True  False    True  False
538       3  29.699118   14.5000   False   True   False   True
562       2  28.000000   13.5000   False   True   False   True
648       3  29.699118    7.5500   False   True   False   True

## Prediction on Test Data

The trained model predicts whether passengers survived or not.

Predicted Output:
- 0 → Did Not Survive
- 1 → Survived

In [33]:
y_test[:10]

665    0
107    1
589    0
884    0
499    0
380    1
358    1
538    0
562    0
648    0
Name: Survived, dtype: int64

In [34]:
model.predict(X_test[:10])

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0])

## Probability Prediction

`predict_proba()` returns the probability of each class.

Example:
- Probability of not surviving
- Probability of surviving

The class with the highest probability becomes the final prediction.

In [36]:
model.predict_proba(X_test[:10])

array([[9.92471934e-01, 7.52806588e-03],
       [9.98986291e-01, 1.01370861e-03],
       [9.98987518e-01, 1.01248222e-03],
       [9.98896429e-01, 1.10357087e-03],
       [9.98878550e-01, 1.12144982e-03],
       [2.86779819e-11, 1.00000000e+00],
       [2.10349190e-03, 9.97896508e-01],
       [9.99000516e-01, 9.99484243e-04],
       [9.97719353e-01, 2.28064720e-03],
       [9.98985246e-01, 1.01475385e-03]])

## Cross Validation

Cross-validation is used to evaluate model stability and generalization performance.

`cv=5` means:
- dataset is divided into 5 parts
- model is trained and validated 5 times

This helps reduce overfitting and gives a more reliable performance estimate.

In [39]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(), X_train, y_train, cv=5)

array([0.712     , 0.776     , 0.808     , 0.77419355, 0.79032258])

## Conclusion

The Gaussian Naive Bayes model successfully predicted passenger survival using the Titanic dataset.

### Key Observations

- GaussianNB is simple and computationally efficient
- Categorical variables must be converted into numerical format
- Missing values should be handled before training
- The model achieved approximately 81% accuracy
- Cross-validation helped evaluate model consistency

This notebook demonstrates a complete machine learning classification workflow including preprocessing, encoding, missing value handling, model training, prediction, probability estimation, and cross-validation using Gaussian Naive Bayes.