# Titanic Survival Prediction using Decision Tree Classifier

## Objective
The goal of this notebook is to predict passenger survival on the Titanic using a Decision Tree Classifier.

The model predicts whether a passenger survived based on:
- passenger class
- age
- gender
- fare amount

## Business Use Case
This type of classification workflow is similar to real-world predictive analytics problems such as:
- customer churn prediction
- loan default prediction
- fraud detection
- insurance claim prediction

In [1]:
import pandas as pd
import numpy as np

## Dataset Overview

The Titanic dataset contains passenger information including:
- passenger class
- age
- gender
- fare
- survival status

Target Variable:
- Survived
  - 1 → survived
  - 0 → did not survive

In [29]:
df=pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.shape

(891, 12)

## Feature Selection

Selected input features:
- Pclass
- Age
- Sex
- Fare

These variables are commonly associated with passenger survival probability.

In [30]:
#splitting into dependent and independent variables
inputs=df[['Pclass','Age','Sex','Fare']]
inputs.head()

   Pclass   Age     Sex     Fare
0       3  22.0    male   7.2500
1       1  38.0  female  71.2833
2       3  26.0  female   7.9250
3       1  35.0  female  53.1000
4       3  35.0    male   8.0500

## Target Variable

The target variable is:
- Survived

This is a binary classification problem where the model predicts whether a passenger survived the disaster.

In [31]:
target=df['Survived']
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

## Handling Categorical Variables

The 'Sex' column is categorical and cannot be directly used by machine learning algorithms.

One-hot encoding is applied using `pd.get_dummies()` to convert gender into numerical representation.

In [32]:
sex_n=pd.get_dummies(inputs['Sex'])
sex_n

     female   male
0     False   True
1      True  False
2      True  False
3      True  False
4     False   True
..      ...    ...
886   False   True
887    True  False
888    True  False
889   False   True
890   False   True

[891 rows x 2 columns]

In [33]:
inputs=pd.concat([inputs,sex_n], axis=1)
inputs.head()

   Pclass   Age     Sex     Fare  female   male
0       3  22.0    male   7.2500   False   True
1       1  38.0  female  71.2833    True  False
2       3  26.0  female   7.9250    True  False
3       1  35.0  female  53.1000    True  False
4       3  35.0    male   8.0500   False   True

## Avoiding Dummy Variable Trap

One dummy column ('male') is removed to avoid redundancy and multicollinearity.

The remaining 'female' column is sufficient to represent gender information.

In [34]:
inputs.drop(['Sex','male'], axis=1, inplace=True)
inputs.head()

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True
3       1  35.0  53.1000    True
4       3  35.0   8.0500   False

## Handling Missing Values

The 'Age' column contains missing values.

Missing ages are replaced using the mean age of the dataset to ensure the model can process all records.

In [35]:
inputs['Age']=inputs['Age'].fillna(inputs['Age'].mean())
inputs.head(10)

   Pclass        Age     Fare  female
0       3  22.000000   7.2500   False
1       1  38.000000  71.2833    True
2       3  26.000000   7.9250    True
3       1  35.000000  53.1000    True
4       3  35.000000   8.0500   False
5       3  29.699118   8.4583   False
6       1  54.000000  51.8625   False
7       3   2.000000  21.0750   False
8       3  27.000000  11.1333    True
9       2  14.000000  30.0708    True

## Train-Test Split

The dataset is divided into:
- Training dataset → used to train the model
- Testing dataset → used to evaluate model performance on unseen data

A test size of 20% is used.

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(inputs,target,test_size=0.2)

In [37]:
X_train.shape

(712, 4)

In [38]:
X_test.shape

(179, 4)

## Decision Tree Classification Model

Decision Tree Classifier is used for binary classification.

The algorithm works by:
1. Splitting data based on feature conditions
2. Creating decision rules
3. Predicting survival outcome based on learned patterns

Advantages:
- interpretable
- handles non-linear relationships
- easy to visualize

In [39]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()

In [41]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

## Model Evaluation

The model is evaluated using accuracy score on the testing dataset.

Accuracy measures the percentage of correctly classified passenger outcomes.

In [43]:
#accuracy
model.score(X_test,y_test)

0.7821229050279329

## Conclusion

The Decision Tree model successfully predicted Titanic passenger survival using demographic and fare-related features.

Key observations:
- Gender and passenger class strongly influenced survival probability
- Missing values were handled using mean imputation
- Categorical variables were converted using one-hot encoding
- The model achieved approximately 78% accuracy on unseen data

This notebook demonstrates a complete supervised machine learning workflow including:
- data preprocessing
- feature engineering
- missing value handling
- categorical encoding
- model training
- model evaluation